spring:
  main:
    banner-mode: off
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/weather
    username: test_user
    password: test_user_pass
  flyway:
    url: jdbc:postgresql://localhost:5432/weather
