name: Deploy release
on:
  release:
    types: [ published ]
jobs:
  docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle/configuration-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          distribution: temurin
          java-version: 17
      - name: Build jar
        run: ./gradlew assemble --no-daemon
      - name: Build docker image
        run: |
          cd app
          TAG_NAME=${GITHUB_REF#"refs/tags/"}
          docker build -t lightning-rod \
            --label="org.opencontainers.image.version=$TAG_NAME" \
            --label="org.opencontainers.image.revision=$GITHUB_SHA" \
            --label="org.opencontainers.image.created=$(date +'%Y-%m-%dT%H:%M:%S')" \
            .
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Publish docker images
        run: |
          TAG_NAME=${GITHUB_REF#"refs/tags/"}
          # strip "v" prefix from tag name
          TAG_NAME=$(echo $TAG_NAME | sed -e 's/^v//')
          echo "Publishing image to ghcr.io/twinklehawk/lightning-rod:$TAG_NAME"
          docker tag lightning-rod ghcr.io/twinklehawk/lightning-rod:$TAG_NAME
          docker tag lightning-rod ghcr.io/twinklehawk/lightning-rod:latest
          docker push ghcr.io/twinklehawk/lightning-rod:$TAG_NAME
          docker push ghcr.io/twinklehawk/lightning-rod:latest
